"""Build the self-improving `sentinel-tech` model from what the agent has learned.

Each rebuild distills trusted cases (verified-resolved or operator-confirmed)
into lessons and worked examples, writes them to models/sentinel-tech/
(Modelfile, knowledge.json, training_data.jsonl) and creates the model in
Ollama on top of the base model. This is knowledge distillation into the
prompt (system lessons + few-shot examples), not weight fine-tuning;
training_data.jsonl is exported so the same cases can be used for a real
LoRA fine-tune on a GPU later.
"""

import json
import logging
import os
import threading
from datetime import datetime, timezone

import httpx

from ..config import MODELS_DIR
from . import store

logger = logging.getLogger(__name__)

LEARNED_DIR = MODELS_DIR / "sentinel-tech"
VERSION_FILE = LEARNED_DIR / "version.json"
MAX_LESSONS = 25
MAX_EXAMPLES = 3
_build_lock = threading.Lock()

BASE_SYSTEM = """You are Sentinel, a senior IT support technician for Windows, macOS and Linux.
You diagnose problems from real diagnostic evidence, explain root causes in plain language,
and recommend safe, specific fixes. Never invent numbers or facts that are not in the evidence."""


def learned_model_name():
    return os.getenv("LEARNED_MODEL_NAME", "sentinel-tech")


def base_model_name():
    return os.getenv("OLLAMA_MODEL", "qwen2.5:3b")


def rebuild_every():
    try:
        return max(1, int(os.getenv("LEARNING_REBUILD_EVERY", "3")))
    except ValueError:
        return 3


def version_info():
    try:
        return json.loads(VERSION_FILE.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {"version": 0, "trusted_cases": 0, "built_at": None, "base_model": None, "lessons": 0}


def _fix_names(case, applied_only=True):
    return [fix["tool_id"] for fix in case.get("fixes", []) if not applied_only or fix.get("status") == "applied"]


def lessons(cases):
    """One line per distinct (issue, root cause) learned from trusted cases, newest first."""
    seen, result = set(), []
    for case in cases:
        if not store.is_trusted(case):
            continue
        cause = (case.get("effective_root_cause") or "").strip()
        key = (" ".join(sorted(set(store.tokenize(case["issue"])))[:8]), cause[:80].lower())
        if not cause or key in seen:
            continue
        seen.add(key)
        fixes = _fix_names(case)
        line = f"- [{case.get('os_type') or 'any OS'}] \"{case['issue'][:140]}\" -> cause: {cause[:220]}"
        if fixes:
            line += f" -> fixed by: {', '.join(fixes)}"
        if case.get("corrected_root_cause"):
            line += " (corrected by a technician)"
        result.append(line)
        if len(result) >= MAX_LESSONS:
            break
    return result


def _example_answer(case):
    return json.dumps({
        "root_cause": case.get("effective_root_cause"),
        "evidence": case.get("evidence", [])[:3],
        "proposed_fixes": [{"tool_id": tool_id, "args": {}} for tool_id in _fix_names(case)],
    })


def _modelfile(base, system, examples, version):
    lines = [
        f"# Sentinel self-improving model v{version} - generated by backend/learning/model_builder.py",
        f"# Built with Qwen (base: {base}). Do not edit by hand; it is regenerated from learned cases.",
        f"FROM {base}",
        "PARAMETER temperature 0.2",
        "PARAMETER num_ctx 8192",
        f'SYSTEM """{system}"""',
    ]
    for case in examples:
        lines.append(f'MESSAGE user """Problem on {case.get("os_type") or "a computer"}: {case["issue"]}"""')
        lines.append(f'MESSAGE assistant """{_example_answer(case)}"""')
    return "\n".join(lines) + "\n"


def export_training_data(cases):
    """Chat-format JSONL of trusted cases, ready for a LoRA fine-tune."""
    rows = []
    for case in cases:
        if not store.is_trusted(case):
            continue
        rows.append(json.dumps({"messages": [
            {"role": "system", "content": BASE_SYSTEM},
            {"role": "user", "content": f"Problem on {case.get('os_type')}: {case['issue']}\nEvidence: {json.dumps(case.get('evidence', []))}"},
            {"role": "assistant", "content": _example_answer(case)},
        ]}))
    return "\n".join(rows) + ("\n" if rows else "")


def build(reason="manual"):
    """Regenerate models/sentinel-tech and (re)create it in Ollama. Returns the new version info."""
    with _build_lock:
        cases = store.list_cases(5000)
        trusted = [case for case in cases if store.is_trusted(case)]
        learned = lessons(cases)
        examples = trusted[:MAX_EXAMPLES]
        version = version_info()["version"] + 1
        base = base_model_name()
        system = BASE_SYSTEM + ("\n\nLessons learned from previously resolved tickets:\n" + "\n".join(learned) if learned else "")

        LEARNED_DIR.mkdir(parents=True, exist_ok=True)
        (LEARNED_DIR / "Modelfile").write_text(_modelfile(base, system, examples, version), encoding="utf-8")
        (LEARNED_DIR / "knowledge.json").write_text(json.dumps({"lessons": learned, "stats": store.stats()}, indent=2), encoding="utf-8")
        (LEARNED_DIR / "training_data.jsonl").write_text(export_training_data(cases), encoding="utf-8")

        messages = []
        for case in examples:
            messages.append({"role": "user", "content": f"Problem on {case.get('os_type') or 'a computer'}: {case['issue']}"})
            messages.append({"role": "assistant", "content": _example_answer(case)})
        host = os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434").rstrip("/")
        body = {"model": learned_model_name(), "from": base, "system": system, "messages": messages, "parameters": {"temperature": 0.2, "num_ctx": 8192}, "stream": False}
        try:
            response = httpx.post(f"{host}/api/create", json=body, timeout=300)
            response.raise_for_status()
            created, error = True, None
        except httpx.HTTPError as exc:
            created, error = False, str(exc)
            logger.warning("Could not create %s in Ollama: %s", learned_model_name(), exc)

        info = {
            "version": version,
            "model": learned_model_name(),
            "base_model": base,
            "trusted_cases": len(trusted),
            "lessons": len(learned),
            "examples": len(examples),
            "built_at": datetime.now(timezone.utc).isoformat(),
            "reason": reason,
            "created_in_ollama": created,
            "error": error,
        }
        VERSION_FILE.write_text(json.dumps(info, indent=2), encoding="utf-8")
        return info


def maybe_rebuild():
    """Rebuild once enough new trusted cases have accumulated since the last build."""
    trusted = sum(1 for case in store.list_cases(5000) if store.is_trusted(case))
    if trusted and trusted - version_info().get("trusted_cases", 0) >= rebuild_every():
        return build(reason=f"auto: {trusted} trusted cases")
    return None
